version: "3"
services:
    app:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/usr/src/app
            - /usr/src/app/node_modules/
            - /usr/src/app/.cache/
            - /usr/src/app/public/
